services:
  db:
    image: pgvector/pgvector:pg17
    ports:
      - '5432:5432'
    restart: always
    environment:
      - 'POSTGRES_DB=ragdb'
      - 'POSTGRES_USER=raguser'
      - 'POSTGRES_PASSWORD=ragpassword'